FROM gitlab/gitlab-ce
# Copied from the base GitLab Docker file
# (https://gitlab.com/gitlab-org/omnibus-gitlab/blob/master/docker/Dockerfile):
# Wrapper to handle signal, trigger runit and reconfigure GitLab
CMD ["/assets/wrapper"]
#
# End of Docker file
#
