#!/usr/bin/env ruby
#
# Script to add custom_hooks directories to 
# existing repositories.
#
# This script is a workaround for the apparent
# lack of general way to statically configure
# custom hooks at project creation.
#
masterCustomHooksDir = "/var/opt/dfst/custom_hooks"
repodir = "/var/opt/gitlab/git-data/repositories"
Dir.chdir(repodir)
Dir['**/*.git'].each do |dir|
    # puts "dir=#{dir}"
    cmd = "ln -s #{masterCustomHooksDir} #{repodir}/#{dir}"
    #puts "cmd=#{cmd}"
    `#{cmd} 2> /dev/null`
end
